const KB={health:'健康、NCD、血压、血糖、血脂、肠脑轴与产品教育。',beauty:'ARTISTRY、Skin Analysis、护肤系列、成分与 Healthy Beauty。',business:'A→B、4×4、Step 1-2-3、公司背景与创业路径。',team:'培训、导师、团队文化、成长与官方支持。',events:'团队活动、官方活动与活动日历。',homecare:'厨房、洗衣、居家清洁、空气与饮水等生活场景。'};
function toggleAI(){const c=document.getElementById('chat');if(!c)return;c.classList.toggle('open');if(c.classList.contains('open'))document.getElementById('q')?.focus()}
function addMsg(t,w){const box=document.getElementById('msgs');if(!box)return;const m=document.createElement('div');m.className='msg '+w;m.textContent=t;box.appendChild(m);box.scrollTop=box.scrollHeight}
function openTool(id){document.getElementById(id)?.classList.add('open')}function closeTool(id){document.getElementById(id)?.classList.remove('open')}function checkResult(v){const r=document.getElementById('checkResult');const m={nutrition:'营养：可以从均衡饮食、蛋白质、蔬果、纤维与饮水开始探索。',movement:'活动：可以从日常步行、力量训练与减少久坐开始探索。',sleep:'睡眠：可以从规律作息、睡眠环境与睡前习惯开始探索。',stress:'压力：可以从休息、社交支持、呼吸练习与时间管理开始探索。'};if(r){r.style.display='block';r.innerHTML='<b>'+m[v]+'</b><br><small>如果你有健康问题，请咨询合格医疗专业人员。</small>';}}function homeScene(v){const r=document.getElementById('homeResult');if(r){r.style.display='block';r.innerHTML='<b>'+v+' Explorer</b><p>下一步可以展示相关产品类别、使用方式、官方资料与常见问题。</p><button class="btn dark" onclick="askAI(\'请介绍'+v+'相关的 Home Care 产品类别\')">问 AI →</button>'}}function aiAnswer(q){const s=q.toLowerCase();if(/ncd|血压|血糖|胆固醇|健康|肠脑/.test(s))return'可以从“教育 → 筛查 → 生活方式 → 产品资料”四层理解。营养补充品不能替代医疗诊断或治疗。';if(/artistry|美容|皮肤|护肤|肤质/.test(s))return'可以先做 Beauty Profile，再根据保湿、油脂、暗沉或紧致等方向进入对应内容。正式产品建议应以当期官方资料为准。';if(/a路|b路|4x4|step|事业|创业/.test(s))return'这套体验会把 A→B、4×4、Step 1-2-3 做成可视化路径，并把你的教学框架和官方规则分开。';if(/团队|培训|奖励/.test(s))return'团队页重点展示学习、导师、训练、活动和成长环境；奖励/收入内容应以当期官方规则与资格条件为准。';if(/home|居家|厨房|洗衣|清洁|空气|饮水/.test(s))return'可以先按生活场景探索 Home Care，再进入具体产品资料。正式产品名称、规格、价格与说明应以 Amway Malaysia 当期官方资料为准。';if(/活动|event/.test(s))return'活动页可区分你的团队活动与官方活动，并链接到 Amway Malaysia 当前活动/培训资源。';return'你可以问：A→B、4×4、Step 1-2-3、NCD、肠脑轴、ARTISTRY、Skin Analysis、团队或活动。'}
function sendAI(){const i=document.getElementById('q'),q=i?.value.trim();if(!q)return;addMsg(q,'user');i.value='';setTimeout(()=>addMsg(aiAnswer(q),'ai'),260)}
function askAI(q){toggleAI();const i=document.getElementById('q');if(i){i.value=q;sendAI()}}
function revealInit(){const els=document.querySelectorAll('.reveal,.stagger');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}
function tilt(){document.querySelectorAll('.hero-visual').forEach(card=>{card.addEventListener('pointermove',e=>{if(matchMedia('(pointer:fine)').matches){const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateY(${x*5}deg) rotateX(${-y*5}deg)`}});card.addEventListener('pointerleave',()=>card.style.transform='')})}
function abInit(){const stage=document.querySelector('.ab-stage');if(!stage)return;const p=document.querySelector('.ab-person'),a=document.querySelector('.node-a'),b=document.querySelector('.node-b'),title=document.querySelector('#abTitle'),copy=document.querySelector('#abCopy');const modes={a:{x:'15%',t:'A 路 · 现状',c:'时间换收入、单点依赖、成长路径受限。'},b:{x:'85%',t:'B 路 · 另一种选择',c:'把学习、产品、客户与团队关系组织成长期经营的路径。'},bridge:{x:'50%',t:'A → B · 转变',c:'不是一夜改变，而是把目标拆成可执行的下一步。'}};function set(k){const m=modes[k];p.style.left=m.x;a.classList.toggle('active',k==='a');b.classList.toggle('active',k==='b');title.textContent=m.t;copy.textContent=m.c;document.querySelectorAll('.ab-controls button').forEach(x=>x.classList.toggle('active',x.dataset.mode===k))}document.querySelectorAll('.ab-controls button').forEach(x=>x.addEventListener('click',()=>set(x.dataset.mode)));set('bridge')}
function hotspots(){const panel=document.querySelector('.hotspot-panel');if(!panel)return;const data={gut:['GUT · 肠道','从饮食、膳食纤维、益生菌与生活方式理解肠道健康。'],brain:['BRAIN · 大脑','肠脑轴是一个教育概念，可用于解释肠道与神经系统之间的双向关联。'],skin:['SKIN · 皮肤','皮肤屏障、微生态与整体生活方式可以一起放进 Healthy Beauty 的故事。']};document.querySelectorAll('.hotspot').forEach(b=>b.addEventListener('click',()=>{const d=data[b.dataset.id];panel.innerHTML=`<b>${d[0]}</b><p>${d[1]}</p>`}))}
function quiz(){const r=document.querySelector('.quiz-result');if(!r)return;document.querySelectorAll('.quiz-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.quiz-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');r.style.display='block';r.innerHTML='<b>Beauty Profile · '+b.dataset.v+'</b><br>下一步可以进入对应护理教育与官方产品系列。'}))}
function counters(){document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count;let n=0;const step=Math.max(1,Math.ceil(target/40));const tick=()=>{n=Math.min(target,n+step);el.textContent=n.toLocaleString();if(n<target)requestAnimationFrame(tick)};const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){tick();io.disconnect()}},{threshold:.5});io.observe(el)})}
revealInit();tilt();abInit();hotspots();quiz();counters();
